Repository SINTEF/ci-cd, pull requests merged in 2023-03, with the labels that each got.

#107 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
Labels: CI/CD

#108 [Auto-generated] Check & update dependencies (`pyproject.toml`)
  pyproject.toml
Labels: CI/CD

#118 Fix typo in auto merge workflow
  .github/workflows/ci_automerge_prs.yml
Labels: bug

#120 Fix GH Actions variable naming
  .github/workflows/ci_automerge_prs.yml
Labels: bug

#121 [Auto-generated] Update dependencies
  .github/workflows/cd_release.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI/CD

#127 Use CODECOV_TOKEN secret in CI
  .github/workflows/_local_ci_tests.yml
Labels: priority/high

#126 Use the proper "ignore" option name for update-deps
  .github/workflows/ci_check_pyproject_dependencies.yml
Labels: priority/high

#115 Use GitHub usernames in changelogs for releases
  .github/workflows/cd_release.yml
  .github/workflows/ci_cd_updated_default_branch.yml
  docs/workflows/cd_release.md
Labels: priority/medium
