Repository SINTEF/ci-cd, pull requests merged in 2023-05, with the labels that each got.

#143 [Auto-generated] Update dependencies
  .pre-commit-config.yaml
Labels: CI/CD

#149 [Auto-generated] Check & update dependencies (`pyproject.toml`)
  pyproject.toml
Labels: CI/CD

#114 Activate auto-merge for pyproject.toml update PRs
  .github/workflows/_local_ci_automerge_dependency_prs.yml
  docs/workflows/ci_automerge_prs.md
  docs/workflows/ci_update_dependencies.md
Labels: priority/low

#128 Add `update-pyproject` pre-commit hook
  .github/workflows/_local_cd_release.yml
  .pre-commit-hooks.yaml
  ci_cd/tasks/update_deps.py
  docs/hooks/index.md
  docs/hooks/update_pyproject.md
Labels: priority/low

#140 Fix ignore functionality (especially for 'version' rules)
  ci_cd/tasks/update_deps.py
  ci_cd/utils.py
  pyproject.toml
  tests/tasks/test_update_deps.py
  tests/test_utils.py
Labels: priority/high

#154 [Auto-generated] Update dependencies
  .github/workflows/cd_release.yml
  .github/workflows/ci_check_pyproject_dependencies.yml
  .github/workflows/ci_update_dependencies.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: CI/CD

#155 [Auto-generated] Check & update dependencies (`pyproject.toml`)
  pyproject.toml
Labels: CI/CD
